# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ingest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ingest.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cingest.proto\"*\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\revent_payload\x18\x0c \x01(\t\"\'\n\x0ePublishRequest\x12\x15\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x06.Event\",\n\x12PublishBulkRequest\x12\x16\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x06.Event\"R\n\x13PublishBulkResponse\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.BulkStatus\x12\x1e\n\x07replies\x18\x02 \x03(\x0b\x32\r.PublishReply\"<\n\x0cPublishReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t*>\n\nBulkStatus\x12\n\n\x06UNKOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07PARTIAL\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x32q\n\x06Ingest\x12+\n\x07Publish\x12\x0f.PublishRequest\x1a\r.PublishReply\"\x00\x12:\n\x0bPublishBulk\x12\x13.PublishBulkRequest\x1a\x14.PublishBulkResponse\"\x00\x62\x06proto3'
)

_BULKSTATUS = _descriptor.EnumDescriptor(
  name='BulkStatus',
  full_name='BulkStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARTIAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=293,
  serialized_end=355,
)
_sym_db.RegisterEnumDescriptor(_BULKSTATUS)

BulkStatus = enum_type_wrapper.EnumTypeWrapper(_BULKSTATUS)
UNKOWN = 0
SUCCESS = 1
PARTIAL = 2
FAILED = 3



_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Event.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_payload', full_name='Event.event_payload', index=1,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=58,
)


_PUBLISHREQUEST = _descriptor.Descriptor(
  name='PublishRequest',
  full_name='PublishRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='PublishRequest.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=99,
)


_PUBLISHBULKREQUEST = _descriptor.Descriptor(
  name='PublishBulkRequest',
  full_name='PublishBulkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='events', full_name='PublishBulkRequest.events', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=145,
)


_PUBLISHBULKRESPONSE = _descriptor.Descriptor(
  name='PublishBulkResponse',
  full_name='PublishBulkResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='PublishBulkResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='replies', full_name='PublishBulkResponse.replies', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=229,
)


_PUBLISHREPLY = _descriptor.Descriptor(
  name='PublishReply',
  full_name='PublishReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='PublishReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='PublishReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='PublishReply.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=291,
)

_PUBLISHREQUEST.fields_by_name['event'].message_type = _EVENT
_PUBLISHBULKREQUEST.fields_by_name['events'].message_type = _EVENT
_PUBLISHBULKRESPONSE.fields_by_name['status'].enum_type = _BULKSTATUS
_PUBLISHBULKRESPONSE.fields_by_name['replies'].message_type = _PUBLISHREPLY
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['PublishRequest'] = _PUBLISHREQUEST
DESCRIPTOR.message_types_by_name['PublishBulkRequest'] = _PUBLISHBULKREQUEST
DESCRIPTOR.message_types_by_name['PublishBulkResponse'] = _PUBLISHBULKRESPONSE
DESCRIPTOR.message_types_by_name['PublishReply'] = _PUBLISHREPLY
DESCRIPTOR.enum_types_by_name['BulkStatus'] = _BULKSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'ingest_pb2'
  # @@protoc_insertion_point(class_scope:Event)
  })
_sym_db.RegisterMessage(Event)

PublishRequest = _reflection.GeneratedProtocolMessageType('PublishRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHREQUEST,
  '__module__' : 'ingest_pb2'
  # @@protoc_insertion_point(class_scope:PublishRequest)
  })
_sym_db.RegisterMessage(PublishRequest)

PublishBulkRequest = _reflection.GeneratedProtocolMessageType('PublishBulkRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHBULKREQUEST,
  '__module__' : 'ingest_pb2'
  # @@protoc_insertion_point(class_scope:PublishBulkRequest)
  })
_sym_db.RegisterMessage(PublishBulkRequest)

PublishBulkResponse = _reflection.GeneratedProtocolMessageType('PublishBulkResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHBULKRESPONSE,
  '__module__' : 'ingest_pb2'
  # @@protoc_insertion_point(class_scope:PublishBulkResponse)
  })
_sym_db.RegisterMessage(PublishBulkResponse)

PublishReply = _reflection.GeneratedProtocolMessageType('PublishReply', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHREPLY,
  '__module__' : 'ingest_pb2'
  # @@protoc_insertion_point(class_scope:PublishReply)
  })
_sym_db.RegisterMessage(PublishReply)



_INGEST = _descriptor.ServiceDescriptor(
  name='Ingest',
  full_name='Ingest',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=357,
  serialized_end=470,
  methods=[
  _descriptor.MethodDescriptor(
    name='Publish',
    full_name='Ingest.Publish',
    index=0,
    containing_service=None,
    input_type=_PUBLISHREQUEST,
    output_type=_PUBLISHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PublishBulk',
    full_name='Ingest.PublishBulk',
    index=1,
    containing_service=None,
    input_type=_PUBLISHBULKREQUEST,
    output_type=_PUBLISHBULKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INGEST)

DESCRIPTOR.services_by_name['Ingest'] = _INGEST

# @@protoc_insertion_point(module_scope)
